[34m[1mwandb[39m[22m: [33mWARNING[39m No relevant files were detected in the specified directory. No code will be logged to your run.
Traceback (most recent call last):
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/scripts/../tests/test.py", line 614, in <module>
    main()
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/scripts/../tests/test.py", line 418, in main
    TestLSTM().test_standard_lstm(
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/tests/test_standard_lstm.py", line 325, in test_standard_lstm
    val_loaders = get_val_loaders(
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/torchmimic/utils.py", line 183, in get_val_loaders
    val_dataset = PhenotypingDataset(
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/torchmimic/data/phenotyping/dataset.py", line 59, in __init__
    self._read_data(root, listfile)
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/torchmimic/data/phenotyping/dataset.py", line 85, in _read_data
    self.reader.read_example(0)["X"]
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/torchmimic/data/readers.py", line 301, in read_example
    (X, header) = self._read_timeseries(name)
  File "/home/grads/k/kingrc15/Continual_Learning/Continual_Learning/torchmimic/data/readers.py", line 261, in _read_timeseries
    with open(os.path.join(self._dataset_dir, ts_filename), "r") as tsfile:
FileNotFoundError: [Errno 2] No such file or directory: '/data/datasets/mimic3-benchmarks/data/phenotyping/train/10022_episode284443_timeseries_intime_2193-05-13_15-40-41_outtime_2193-05-15_12-05-16.csv'
Experiment dir: ./exp/Test_phen_west_baseline
['/data/datasets/mimic3-benchmarks/data/phenotyping', '/data/datasets/eICU2MIMIC/phenotyping_split']